# Generated by Django 4.2.2 on 2023-07-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_banner_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(upload_to='static/featured_image_%Y_%m_%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='static/featured_image_%Y_%m_%d'),
        ),
    ]
