# Generated by Django 4.2.2 on 2023-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_banner_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
